title: Sara Murley
description: Data science for public policy, social science, and applied research0

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
logo: "/assets/favicon.png"
favicon: "/assets/favicon.png"
include:
  - _includes/head_custom.html

minimal_mistakes:
  masthead: true

plugins:
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:path/

author:
  name   : "Sara Murley"
  avatar : "/assets/profile.jpg"   # optional
  bio    : "M.S. in Data Science for Public Policy at Georgetown University."
  location: "Washington, DC"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:slm333@georgetown.edu"
    - label: "Phone"
      icon: "fas fa-phone"
      url: "tel:+16126709950"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sara-murley"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/sara-murley"
